#!/bin/sh
set -eu

uci -q batch <<'EOF'
set system.@system[0].zram_size_mb='512'
set system.@system[0].zram_comp_algo='lz4'
set network.globals.packet_steering='1'
EOF
uci -q commit system
uci -q commit network

exit 0
