#!/bin/sh
set -eu

# Own only protocol/address defaults. Device profiles remain responsible for
# physical interface discovery and never depend on ethX enumeration order.
uci -q batch <<'EOF'
set network.lan.proto='static'
set network.lan.ipaddr='192.168.2.1'
set network.lan.netmask='255.255.255.0'
set network.lan.ip6assign='64'
set network.lan.delegate='0'
set network.wan.proto='dhcp'
set network.wan6.proto='dhcpv6'
set dhcp.lan='dhcp'
set dhcp.lan.interface='lan'
set dhcp.lan.start='32'
set dhcp.lan.limit='232'
set dhcp.lan.leasetime='12h'
set dhcp.lan.ra='relay'
set dhcp.lan.dhcpv6='relay'
set dhcp.lan.ndp='relay'
set dhcp.wan='dhcp'
set dhcp.wan.interface='wan'
set dhcp.wan.ignore='1'
set dhcp.wan.ra='relay'
set dhcp.wan.dhcpv6='relay'
set dhcp.wan.ndp='relay'
set dhcp.wan.master='1'
EOF
uci -q commit network
uci -q commit dhcp

exit 0
